using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NKHook6.Api.Enums
{
    public enum DefaultTowerIds
    {
        DartMonkey,
        BoomerangMonkey,
        BombShooter,
        TackShooter,
        IceMonkey,
        GlueGunner,
        SniperMonkey,
        MonkeySub,
        MonkeyBuccaneer,
        BuccaneerLesserPlane,
        BuccaneerGreaterPlane,
        BuccaneerLesserPlaneCamo,
        BuccaneerGreaterPlaneCamo,
        MonkeyAce,
        HeliPilot,
        Marine,
        MortarMonkey,
        WizardMonkey,
        Phoenix,
        PermaPhoenix,
        LordPhoenix,
        SuperMonkey,
        SunAvatarMini,
        TrueSunAvatarMini,
        SpectreA,
        SpectreC,
        SpectreVA,
        SpectreVC,
        NinjaMonkey,
        Alchemist,
        Druid,
        BananaFarm,
        SpikeFactory,
        MonkeyVillage,
        EngineerMonkey,
        Sentry,
        SentryCrushing,
        SentryBoom,
        SentryCold,
        SentryEnergy,
        SentryParagon,
        Quincy,
        StrikerJones,
        Ezili,
        SacrificialTotem,
        CaptainChurchill,
        Gwendolin,
        Benjamin,
        PatFusty,
        ObynGreenfoot,
        NaturesWardTotem,
        Adora,
        BallOfLight__Tower,
        AdmiralBrickell,
        Etienne,
        Drone,
        UAV,
        UCAV
    }
}
