using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NKHook6.Api.Utilities
{
    public enum DefaultBloonIds
    {
        Red,
        RedRegrow,
        RedRegrowCamo,
        RedCamo,
        Blue,
        BlueRegrow,
        BlueRegrowCamo,
        BlueCamo,
        Green,
        GreenRegrow,
        GreenRegrowCamo,
        GreenCamo,
        Yellow,
        YellowRegrow,
        YellowRegrowCamo,
        YellowCamo,
        Pink,
        PinkRegrow,
        PinkRegrowCamo,
        PinkCamo,
        Black,
        BlackRegrow,
        BlackRegrowCamo,
        BlackCamo,
        White,
        WhiteRegrow,
        WhiteRegrowCamo,
        WhiteCamo,
        Purple,
        PurpleRegrow,
        PurpleRegrowCamo,
        PurpleCamo,
        Zebra,
        ZebraRegrow,
        ZebraRegrowCamo,
        ZebraCamo,
        Lead,
        LeadRegrow,
        LeadRegrowFortified,
        LeadRegrowFortifiedCamo,
        LeadRegrowCamo,
        LeadFortified,
        LeadFortifiedCamo,
        LeadCamo,
        Rainbow,
        RainbowRegrow,
        RainbowRegrowCamo,
        RainbowCamo,
        Ceramic,
        CeramicRegrow,
        CeramicRegrowFortified,
        CeramicRegrowFortifiedCamo,
        CeramicRegrowCamo,
        CeramicFortified,
        CeramicFortifiedCamo,
        CeramicCamo,
        Moab,
        MoabFortified,
        Bfb,
        BfbFortified,
        Zomg,
        ZomgFortified,
        Ddt,
        DdtFortified,
        DdtFortifiedCamo,
        DdtCamo,
        Bad,
        BadFortified,
        TestBloon
    }
}
